# Team lists for Smack Chat rooms. Independent of team_aliases.py on
# purpose — that file's codes have to exactly match SportsDataIO's API for
# live game lookups; these are just room labels for a chat feature, so
# they don't need that same precision. Codes here just need to be unique
# and URL-safe.
#
# NFL/NBA/MLB/NHL are complete (every team in the league). NCAAF/NCAAB/
# NCAAWB cover major, widely-recognized programs across all the Power
# conferences rather than every D1 school — full FBS is 130+ teams and
# full D1 basketball is 350+, which isn't practical to hand-list here.
# WNBA is complete (only ~13 teams).

CHAT_LEAGUES = {
    "nfl": {
        "ARI": "Cardinals", "ATL": "Falcons", "BAL": "Ravens", "BUF": "Bills",
        "CAR": "Panthers", "CHI": "Bears", "CIN": "Bengals", "CLE": "Browns",
        "DAL": "Cowboys", "DEN": "Broncos", "DET": "Lions", "GB": "Packers",
        "HOU": "Texans", "IND": "Colts", "JAX": "Jaguars", "KC": "Chiefs",
        "LAC": "Chargers", "LAR": "Rams", "LV": "Raiders", "MIA": "Dolphins",
        "MIN": "Vikings", "NE": "Patriots", "NO": "Saints", "NYG": "Giants",
        "NYJ": "Jets", "PHI": "Eagles", "PIT": "Steelers", "SEA": "Seahawks",
        "SF": "49ers", "TB": "Buccaneers", "TEN": "Titans", "WAS": "Commanders",
    },
    "nba": {
        "ATL": "Hawks", "BOS": "Celtics", "BKN": "Nets", "CHA": "Hornets",
        "CHI": "Bulls", "CLE": "Cavaliers", "DAL": "Mavericks", "DEN": "Nuggets",
        "DET": "Pistons", "GS": "Warriors", "HOU": "Rockets", "IND": "Pacers",
        "LAC": "Clippers", "LAL": "Lakers", "MEM": "Grizzlies", "MIA": "Heat",
        "MIL": "Bucks", "MIN": "Timberwolves", "NO": "Pelicans", "NY": "Knicks",
        "OKC": "Thunder", "ORL": "Magic", "PHI": "76ers", "PHO": "Suns",
        "POR": "Trail Blazers", "SAC": "Kings", "SA": "Spurs", "TOR": "Raptors",
        "UTA": "Jazz", "WAS": "Wizards",
    },
    "mlb": {
        "ARI": "Diamondbacks", "ATL": "Braves", "BAL": "Orioles", "BOS": "Red Sox",
        "CHC": "Cubs", "CHW": "White Sox", "CIN": "Reds", "CLE": "Guardians",
        "COL": "Rockies", "DET": "Tigers", "HOU": "Astros", "KC": "Royals",
        "LAA": "Angels", "LAD": "Dodgers", "MIA": "Marlins", "MIL": "Brewers",
        "MIN": "Twins", "NYM": "Mets", "NYY": "Yankees", "ATH": "Athletics",
        "PHI": "Phillies", "PIT": "Pirates", "SD": "Padres", "SF": "Giants",
        "SEA": "Mariners", "STL": "Cardinals", "TB": "Rays", "TEX": "Rangers",
        "TOR": "Blue Jays", "WSH": "Nationals",
    },
    "nhl": {
        "ANA": "Ducks", "UTA": "Mammoth", "BOS": "Bruins", "BUF": "Sabres",
        "CGY": "Flames", "CAR": "Hurricanes", "CHI": "Blackhawks", "COL": "Avalanche",
        "CBJ": "Blue Jackets", "DAL": "Stars", "DET": "Red Wings", "EDM": "Oilers",
        "FLA": "Panthers", "LA": "Kings", "MIN": "Wild", "MON": "Canadiens",
        "NAS": "Predators", "NJ": "Devils", "NYI": "Islanders", "NYR": "Rangers",
        "OTT": "Senators", "PHI": "Flyers", "PIT": "Penguins", "SJ": "Sharks",
        "SEA": "Kraken", "STL": "Blues", "TB": "Lightning", "TOR": "Maple Leafs",
        "VAN": "Canucks", "VEG": "Golden Knights", "WAS": "Capitals", "WPG": "Jets",
    },
    "wnba": {
        "ATL": "Dream", "CHI": "Sky", "CON": "Sun", "DAL": "Wings",
        "GS": "Valkyries", "IND": "Fever", "LA": "Sparks", "LV": "Aces",
        "MIN": "Lynx", "NY": "Liberty", "PHO": "Mercury", "SEA": "Storm",
        "WAS": "Mystics",
    },
    "sec": {
        "ALA": "Alabama", "ARK": "Arkansas", "AUB": "Auburn", "FLA": "Florida",
        "UGA": "Georgia", "KY": "Kentucky", "LSU": "LSU", "MSST": "Mississippi State",
        "MIZ": "Missouri", "OU": "Oklahoma", "MISS": "Ole Miss", "SC": "South Carolina",
        "TENN": "Tennessee", "TEX": "Texas", "TAMU": "Texas A&M", "VAN": "Vanderbilt",
    },
    "bigten": {
        "ILL": "Illinois", "IND": "Indiana", "IOWA": "Iowa", "MD": "Maryland",
        "MICH": "Michigan", "MSU": "Michigan State", "MINN": "Minnesota",
        "NEB": "Nebraska", "NW": "Northwestern", "OSU": "Ohio State", "ORE": "Oregon",
        "PSU": "Penn State", "PUR": "Purdue", "RUT": "Rutgers", "UCLA": "UCLA",
        "USC": "USC", "UW": "Washington", "WISC": "Wisconsin",
    },
    "big12": {
        "ARIZ": "Arizona", "ASU": "Arizona State", "BAY": "Baylor", "BYU": "BYU",
        "CIN": "Cincinnati", "COLO": "Colorado", "HOU": "Houston", "KU": "Kansas",
        "KSU": "Kansas State", "OKST": "Oklahoma State", "TCU": "TCU",
        "TTU": "Texas Tech", "UCF": "UCF", "UTAH": "Utah", "WVU": "West Virginia",
        "ISU": "Iowa State",
    },
    "acc": {
        "BC": "Boston College", "CAL": "California", "CLEM": "Clemson", "DUKE": "Duke",
        "FSU": "Florida State", "GT": "Georgia Tech", "LOU": "Louisville",
        "MIAFL": "Miami", "NCST": "NC State", "UNC": "North Carolina", "PITT": "Pitt",
        "SMU": "SMU", "STAN": "Stanford", "SYR": "Syracuse", "UVA": "Virginia",
        "VT": "Virginia Tech", "WAKE": "Wake Forest",
    },
    "ncaab": {
        "ALA": "Alabama", "ARIZ": "Arizona", "AUB": "Auburn", "BAY": "Baylor",
        "BYU": "BYU", "UCONN": "UConn", "DUKE": "Duke", "FLA": "Florida",
        "GONZ": "Gonzaga", "UGA": "Georgia", "HOU": "Houston", "ILL": "Illinois",
        "IND": "Indiana", "IOWA": "Iowa", "ISU": "Iowa State", "KU": "Kansas",
        "KSU": "Kansas State", "KY": "Kentucky", "LOU": "Louisville", "MICH": "Michigan",
        "MSU": "Michigan State", "MIZ": "Missouri", "UNC": "North Carolina",
        "OSU": "Ohio State", "OU": "Oklahoma", "ORE": "Oregon", "PUR": "Purdue",
        "SDSU": "San Diego State", "TENN": "Tennessee", "TEX": "Texas",
        "TAMU": "Texas A&M", "UCLA": "UCLA", "USC": "USC", "VILL": "Villanova",
        "UVA": "Virginia", "WISC": "Wisconsin", "MARQ": "Marquette", "CREI": "Creighton",
        "MSST": "Mississippi State", "MISS": "Ole Miss", "SC": "South Carolina",
        "TCU": "TCU", "TTU": "Texas Tech", "XAV": "Xavier", "SLU": "Saint Louis",
    },
    "ncaawb": {
        "SC": "South Carolina", "UCONN": "UConn", "IOWA": "Iowa", "LSU": "LSU",
        "STAN": "Stanford", "UCLA": "UCLA", "USC": "USC", "TENN": "Tennessee",
        "NOTRE": "Notre Dame", "OSU": "Ohio State", "TEX": "Texas", "UNC": "North Carolina",
        "DUKE": "Duke", "BAY": "Baylor", "OU": "Oklahoma", "KY": "Kentucky",
        "UGA": "Georgia", "IND": "Indiana", "VT": "Virginia Tech", "MD": "Maryland",
        "NCST": "NC State", "COLO": "Colorado", "UTAH": "Utah", "MISS": "Ole Miss",
    },
    "mls": {
        "ATLU": "Atlanta United FC", "CLT": "Charlotte FC", "CHI": "Chicago Fire FC",
        "CLB": "Columbus Crew", "DC": "D.C. United", "CIN": "FC Cincinnati",
        "MIA": "Inter Miami CF", "MTL": "CF Montreal", "NSH": "Nashville SC",
        "NE": "New England Revolution", "NYC": "New York City FC", "NYRB": "New York Red Bulls",
        "ORL": "Orlando City SC", "PHI": "Philadelphia Union", "TOR": "Toronto FC",
        "ATX": "Austin FC", "COL": "Colorado Rapids", "DAL": "FC Dallas",
        "HOU": "Houston Dynamo FC", "LAG": "LA Galaxy", "LAFC": "Los Angeles FC",
        "MIN": "Minnesota United FC", "POR": "Portland Timbers", "RSL": "Real Salt Lake",
        "SD": "San Diego FC", "SJ": "San Jose Earthquakes", "SEA": "Seattle Sounders FC",
        "SKC": "Sporting Kansas City", "STL": "St. Louis City SC", "VAN": "Vancouver Whitecaps FC",
    },
    "epl": {
        "BOU": "AFC Bournemouth", "ARS": "Arsenal", "AVL": "Aston Villa",
        "BRE": "Brentford", "BHA": "Brighton & Hove Albion", "CHE": "Chelsea",
        "COV": "Coventry City", "CRY": "Crystal Palace", "EVE": "Everton",
        "FUL": "Fulham", "HUL": "Hull City", "IPS": "Ipswich Town",
        "LEE": "Leeds United", "LIV": "Liverpool", "MCI": "Manchester City",
        "MUN": "Manchester United", "NEW": "Newcastle United", "NFO": "Nottingham Forest",
        "SUN": "Sunderland", "TOT": "Tottenham Hotspur",
    },
    "laliga": {
        "ATH": "Athletic Bilbao", "ATM": "Atletico Madrid", "OSA": "CA Osasuna",
        "CEL": "Celta Vigo", "ALA": "Deportivo Alaves", "DEP": "Deportivo La Coruna",
        "ELC": "Elche CF", "ESP": "RCD Espanyol", "BAR": "FC Barcelona",
        "GET": "Getafe CF", "LEV": "Levante UD", "MAL": "Malaga CF",
        "RAC": "Racing Santander", "RAY": "Rayo Vallecano", "BET": "Real Betis",
        "RMA": "Real Madrid", "RSO": "Real Sociedad", "SEV": "Sevilla FC",
        "VAL": "Valencia CF", "VIL": "Villarreal CF",
    },
    "bundesliga": {
        "AUG": "FC Augsburg", "B04": "Bayer 04 Leverkusen", "FCB": "FC Bayern Munich",
        "BVB": "Borussia Dortmund", "BMG": "Borussia Monchengladbach", "SGE": "Eintracht Frankfurt",
        "SCF": "SC Freiburg", "RBL": "RB Leipzig", "TSG": "TSG 1899 Hoffenheim",
        "M05": "FSV Mainz 05", "FCU": "FC Union Berlin", "VFB": "VfB Stuttgart",
        "SVW": "SV Werder Bremen", "KOE": "FC Cologne", "HSV": "Hamburg SV",
        "S04": "FC Schalke 04", "ELV": "Elversberg", "SCP": "Paderborn",
    },
    "seriea": {
        "MIL": "AC Milan", "MON": "AC Monza", "FIO": "ACF Fiorentina",
        "ROM": "AS Roma", "ATA": "Atalanta BC", "BOL": "Bologna FC 1909",
        "CAG": "Cagliari Calcio", "COM": "Como 1907", "FRO": "Frosinone Calcio",
        "GEN": "Genoa CFC", "INT": "Inter Milan", "JUV": "Juventus FC",
        "PAR": "Parma Calcio 1913", "LAZ": "S.S. Lazio", "NAP": "SSC Napoli",
        "TOR": "Torino FC", "LEC": "U.S. Lecce", "SAS": "U.S. Sassuolo Calcio",
        "UDI": "Udinese Calcio", "VEN": "Venezia FC",
    },
}
