# Maps each team's SportsDataIO abbreviation to a list of names/nicknames a
# person might actually type when searching — city, mascot, full name, and
# common short forms. Search matches against any of these, case-insensitive.
#
# Covers the four major leagues where fans reliably know team names by heart.
# For leagues without an explicit entry here (college sports, soccer, etc.),
# search falls back to matching directly against whatever the API returns.

TEAM_ALIASES = {
    "nfl": {
        "ARI": ["arizona", "cardinals", "arizona cardinals"],
        "ATL": ["atlanta", "falcons", "atlanta falcons"],
        "BAL": ["baltimore", "ravens", "baltimore ravens"],
        "BUF": ["buffalo", "bills", "buffalo bills"],
        "CAR": ["carolina", "panthers", "carolina panthers"],
        "CHI": ["chicago", "bears", "chicago bears"],
        "CIN": ["cincinnati", "bengals", "cincinnati bengals"],
        "CLE": ["cleveland", "browns", "cleveland browns"],
        "DAL": ["dallas", "cowboys", "dallas cowboys"],
        "DEN": ["denver", "broncos", "denver broncos"],
        "DET": ["detroit", "lions", "detroit lions"],
        "GB": ["green bay", "packers", "green bay packers"],
        "HOU": ["houston", "texans", "houston texans"],
        "IND": ["indianapolis", "colts", "indianapolis colts"],
        "JAX": ["jacksonville", "jaguars", "jacksonville jaguars"],
        "KC": ["kansas city", "chiefs", "kansas city chiefs"],
        "LAC": ["los angeles chargers", "la chargers", "chargers"],
        "LAR": ["los angeles rams", "la rams", "rams"],
        "LV": ["las vegas", "raiders", "las vegas raiders"],
        "MIA": ["miami", "dolphins", "miami dolphins"],
        "MIN": ["minnesota", "vikings", "minnesota vikings"],
        "NE": ["new england", "patriots", "new england patriots"],
        "NO": ["new orleans", "saints", "new orleans saints"],
        "NYG": ["new york giants", "ny giants", "giants"],
        "NYJ": ["new york jets", "ny jets", "jets"],
        "PHI": ["philadelphia", "eagles", "philadelphia eagles"],
        "PIT": ["pittsburgh", "steelers", "pittsburgh steelers"],
        "SEA": ["seattle", "seahawks", "seattle seahawks"],
        "SF": ["san francisco", "49ers", "niners", "san francisco 49ers"],
        "TB": ["tampa bay", "buccaneers", "bucs", "tampa bay buccaneers"],
        "TEN": ["tennessee", "titans", "tennessee titans"],
        "WAS": ["washington", "commanders", "washington commanders"],
    },
    "nba": {
        "ATL": ["atlanta", "hawks", "atlanta hawks"],
        "BOS": ["boston", "celtics", "boston celtics"],
        "BKN": ["brooklyn", "nets", "brooklyn nets"],
        "CHA": ["charlotte", "hornets", "charlotte hornets"],
        "CHI": ["chicago", "bulls", "chicago bulls"],
        "CLE": ["cleveland", "cavaliers", "cavs", "cleveland cavaliers"],
        "DAL": ["dallas", "mavericks", "mavs", "dallas mavericks"],
        "DEN": ["denver", "nuggets", "denver nuggets"],
        "DET": ["detroit", "pistons", "detroit pistons"],
        "GS": ["golden state", "warriors", "golden state warriors"],
        "HOU": ["houston", "rockets", "houston rockets"],
        "IND": ["indiana", "pacers", "indiana pacers"],
        "LAC": ["los angeles clippers", "la clippers", "clippers"],
        "LAL": ["los angeles lakers", "la lakers", "lakers"],
        "MEM": ["memphis", "grizzlies", "memphis grizzlies"],
        "MIA": ["miami", "heat", "miami heat"],
        "MIL": ["milwaukee", "bucks", "milwaukee bucks"],
        "MIN": ["minnesota", "timberwolves", "wolves", "minnesota timberwolves"],
        "NO": ["new orleans", "pelicans", "new orleans pelicans"],
        "NY": ["new york", "knicks", "new york knicks"],
        "OKC": ["oklahoma city", "thunder", "oklahoma city thunder"],
        "ORL": ["orlando", "magic", "orlando magic"],
        "PHI": ["philadelphia", "76ers", "sixers", "philadelphia 76ers"],
        "PHO": ["phoenix", "suns", "phoenix suns"],
        "POR": ["portland", "trail blazers", "blazers", "portland trail blazers"],
        "SAC": ["sacramento", "kings", "sacramento kings"],
        "SA": ["san antonio", "spurs", "san antonio spurs"],
        "TOR": ["toronto", "raptors", "toronto raptors"],
        "UTA": ["utah", "jazz", "utah jazz"],
        "WAS": ["washington", "wizards", "washington wizards"],
    },
    "mlb": {
        "ARI": ["arizona", "diamondbacks", "dbacks", "arizona diamondbacks"],
        "ATL": ["atlanta", "braves", "atlanta braves"],
        "BAL": ["baltimore", "orioles", "baltimore orioles"],
        "BOS": ["boston", "red sox", "boston red sox"],
        "CHC": ["chicago cubs", "cubs"],
        "CHW": ["chicago white sox", "white sox"],
        "CIN": ["cincinnati", "reds", "cincinnati reds"],
        "CLE": ["cleveland", "guardians", "cleveland guardians"],
        "COL": ["colorado", "rockies", "colorado rockies"],
        "DET": ["detroit", "tigers", "detroit tigers"],
        "HOU": ["houston", "astros", "houston astros"],
        "KC": ["kansas city", "royals", "kansas city royals"],
        "LAA": ["los angeles angels", "la angels", "angels"],
        "LAD": ["los angeles dodgers", "la dodgers", "dodgers"],
        "MIA": ["miami", "marlins", "miami marlins"],
        "MIL": ["milwaukee", "brewers", "milwaukee brewers"],
        "MIN": ["minnesota", "twins", "minnesota twins"],
        "NYM": ["new york mets", "ny mets", "mets"],
        "NYY": ["new york yankees", "ny yankees", "yankees"],
        "ATH": ["oakland", "athletics", "a's", "oakland athletics"],
        "PHI": ["philadelphia", "phillies", "philadelphia phillies"],
        "PIT": ["pittsburgh", "pirates", "pittsburgh pirates"],
        "SD": ["san diego", "padres", "san diego padres"],
        "SF": ["san francisco", "giants", "san francisco giants"],
        "SEA": ["seattle", "mariners", "seattle mariners"],
        "STL": ["st. louis", "st louis", "cardinals", "st. louis cardinals"],
        "TB": ["tampa bay", "rays", "tampa bay rays"],
        "TEX": ["texas", "rangers", "texas rangers"],
        "TOR": ["toronto", "blue jays", "toronto blue jays"],
        "WSH": ["washington", "nationals", "washington nationals"],
    },
    "nhl": {
        "ANA": ["anaheim", "ducks", "anaheim ducks"],
        "UTA": ["utah", "mammoth", "utah mammoth", "utah hockey club"],
        "BOS": ["boston", "bruins", "boston bruins"],
        "BUF": ["buffalo", "sabres", "buffalo sabres"],
        "CGY": ["calgary", "flames", "calgary flames"],
        "CAR": ["carolina", "hurricanes", "carolina hurricanes"],
        "CHI": ["chicago", "blackhawks", "chicago blackhawks"],
        "COL": ["colorado", "avalanche", "avs", "colorado avalanche"],
        "CBJ": ["columbus", "blue jackets", "columbus blue jackets"],
        "DAL": ["dallas", "stars", "dallas stars"],
        "DET": ["detroit", "red wings", "detroit red wings"],
        "EDM": ["edmonton", "oilers", "edmonton oilers"],
        "FLA": ["florida", "panthers", "florida panthers"],
        "LA": ["los angeles", "kings", "los angeles kings"],
        "MIN": ["minnesota", "wild", "minnesota wild"],
        "MON": ["montreal", "canadiens", "habs", "montreal canadiens"],
        "NAS": ["nashville", "predators", "preds", "nashville predators"],
        "NJ": ["new jersey", "devils", "new jersey devils"],
        "NYI": ["new york islanders", "ny islanders", "islanders"],
        "NYR": ["new york rangers", "ny rangers", "rangers"],
        "OTT": ["ottawa", "senators", "sens", "ottawa senators"],
        "PHI": ["philadelphia", "flyers", "philadelphia flyers"],
        "PIT": ["pittsburgh", "penguins", "pens", "pittsburgh penguins"],
        "SJ": ["san jose", "sharks", "san jose sharks"],
        "SEA": ["seattle", "kraken", "seattle kraken"],
        "STL": ["st. louis", "st louis", "blues", "st. louis blues"],
        "TB": ["tampa bay", "lightning", "tampa bay lightning"],
        "TOR": ["toronto", "maple leafs", "leafs", "toronto maple leafs"],
        "VAN": ["vancouver", "canucks", "vancouver canucks"],
        "VEG": ["vegas", "golden knights", "vegas golden knights"],
        "WAS": ["washington", "capitals", "caps", "washington capitals"],
        "WPG": ["winnipeg", "jets", "winnipeg jets"],
    },
    "ncaaf": {
        # Real codes verified against SportsDataIO's actual Teams endpoint
        # (via /api/admin/check-team-codes) — not guessed. Covers major/
        # recognizable FBS programs rather than all 275 real teams in the
        # league (which includes many small FCS programs). School name is
        # the primary alias since that's how college fans actually search,
        # with the real mascot (from the API) added as a secondary alias.
        "ALA": ["alabama", "crimson tide"], "ARK": ["arkansas", "razorbacks"],
        "AUBRN": ["auburn", "tigers"], "FL": ["florida", "gators"],
        "GA": ["georgia", "bulldogs"], "UK": ["kentucky", "wildcats"],
        "LSU": ["lsu", "louisiana state", "tigers"], "MISS": ["ole miss", "mississippi", "rebels"],
        "MSPST": ["mississippi state", "bulldogs"], "MISSR": ["missouri", "tigers"],
        "OKL": ["oklahoma", "sooners"], "SC": ["south carolina", "gamecocks"],
        "TENN": ["tennessee", "volunteers", "vols"], "TX": ["texas", "longhorns"],
        "TXAM": ["texas a&m", "texas am", "aggies"], "VAND": ["vanderbilt", "commodores"],
        "ILL": ["illinois", "fighting illini"], "IND": ["indiana", "hoosiers"],
        "IOWA": ["iowa", "hawkeyes"], "MARY": ["maryland", "terrapins", "terps"],
        "MICH": ["michigan", "wolverines"], "MST": ["michigan state", "spartans"],
        "MINNST": ["minnesota", "golden gophers"], "NEBR": ["nebraska", "cornhuskers"],
        "NW": ["northwestern", "wildcats"], "OHIOST": ["ohio state", "buckeyes"],
        "ORE": ["oregon", "ducks"], "PENNST": ["penn state", "nittany lions"],
        "PUR": ["purdue", "boilermakers"], "RUTGER": ["rutgers", "scarlet knights"],
        "UCLA": ["ucla", "bruins"], "USC": ["usc", "trojans"],
        "WASH": ["washington", "huskies"], "WISC": ["wisconsin", "badgers"],
        "ARZ": ["arizona", "wildcats"], "ARZST": ["arizona state", "sun devils"],
        "BAYL": ["baylor", "bears"], "BYU": ["byu", "cougars"],
        "CIN": ["cincinnati", "bearcats"], "COL": ["colorado", "buffaloes"],
        "HOU": ["houston", "cougars"], "KAN": ["kansas", "jayhawks"],
        "KANST": ["kansas state", "wildcats"], "OKST": ["oklahoma state", "cowboys"],
        "TCU": ["tcu", "horned frogs"], "TXTECH": ["texas tech", "red raiders"],
        "UCF": ["ucf", "knights"], "UTAH": ["utah", "utes"],
        "WVIR": ["west virginia", "mountaineers"], "IOWAST": ["iowa state", "cyclones"],
        "BOSCOL": ["boston college", "eagles"], "CAH": ["california", "cal", "golden bears"],
        "CLMSN": ["clemson", "tigers"], "DUKE": ["duke", "blue devils"],
        "FLST": ["florida state", "seminoles"], "GTECH": ["georgia tech", "yellow jackets"],
        "LOU": ["louisville", "cardinals"], "MIA": ["miami", "hurricanes"],
        "NCST": ["nc state", "wolfpack"], "NCAR": ["north carolina", "tar heels"],
        "PITT": ["pittsburgh", "pitt", "panthers"], "SMU": ["smu", "mustangs"],
        "STAN": ["stanford", "cardinal"], "SYRA": ["syracuse", "orange"],
        "VIR": ["virginia", "cavaliers"], "VTECH": ["virginia tech", "hokies"],
        "WAKE": ["wake forest", "demon deacons"], "ND": ["notre dame", "fighting irish"],
        "NAVY": ["navy", "midshipmen"], "ARMY": ["army", "black knights"],
        "BOISE": ["boise state", "broncos"], "MPHS": ["memphis", "tigers"],
        "TULANE": ["tulane", "green wave"], "TULSA": ["tulsa", "golden hurricane"],
        "APPLST": ["appalachian state", "app state", "mountaineers"],
        "COAST": ["coastal carolina", "chanticleers"], "JMAD": ["james madison", "dukes"],
        "LOULAF": ["louisiana", "ul lafayette", "ragin cajuns"],
        "MARSH": ["marshall", "thundering herd"], "SDST": ["san diego state", "aztecs"],
        "NEVADA": ["nevada", "wolf pack"], "HAWAII": ["hawaii", "rainbow warriors"],
        "UTSA": ["utsa", "roadrunners"], "UAB": ["uab", "blazers"],
        "TROY": ["troy", "trojans"], "LIBRTY": ["liberty", "flames"],
        "UNLV": ["unlv", "runnin rebels"],
    },
    "ncaab": {
        # Real codes verified against SportsDataIO's actual Teams endpoint.
        # This feed covers 1,300+ teams across every division (D1 through
        # NAIA/juco) — this covers major, recognizable D1 programs only,
        # not every school in the feed.
        "ALA": ["alabama", "crimson tide"], "ARK": ["arkansas", "razorbacks"],
        "AUBRN": ["auburn", "tigers"], "FL": ["florida", "gators"],
        "GA": ["georgia", "bulldogs"], "UK": ["kentucky", "wildcats"],
        "LSU": ["lsu", "louisiana state", "tigers"], "MISS": ["ole miss", "mississippi", "rebels"],
        "MSPST": ["mississippi state", "bulldogs"], "MISSR": ["missouri", "tigers"],
        "OKL": ["oklahoma", "sooners"], "SC": ["south carolina", "gamecocks"],
        "TENN": ["tennessee", "volunteers", "vols"], "TX": ["texas", "longhorns"],
        "TXAM": ["texas a&m", "texas am", "aggies"], "VAND": ["vanderbilt", "commodores"],
        "ILL": ["illinois", "fighting illini"], "IND": ["indiana", "hoosiers"],
        "IOWA": ["iowa", "hawkeyes"], "MARY": ["maryland", "terrapins", "terps"],
        "MICH": ["michigan", "wolverines"], "MST": ["michigan state", "spartans"],
        "MINNST": ["minnesota", "golden gophers"], "NEBR": ["nebraska", "cornhuskers"],
        "NW": ["northwestern", "wildcats"], "OHIOST": ["ohio state", "buckeyes"],
        "ORE": ["oregon", "ducks"], "PENNST": ["penn state", "nittany lions"],
        "PUR": ["purdue", "boilermakers"], "RUTGER": ["rutgers", "scarlet knights"],
        "UCLA": ["ucla", "bruins"], "USC": ["usc", "trojans"],
        "WASH": ["washington", "huskies"], "WISC": ["wisconsin", "badgers"],
        "ARZ": ["arizona", "wildcats"], "ARZST": ["arizona state", "sun devils"],
        "BAYL": ["baylor", "bears"], "BYU": ["byu", "cougars"],
        "CIN": ["cincinnati", "bearcats"], "COL": ["colorado", "buffaloes"],
        "HOU": ["houston", "cougars"], "KAN": ["kansas", "jayhawks"],
        "KANST": ["kansas state", "wildcats"], "OKST": ["oklahoma state", "cowboys"],
        "TCU": ["tcu", "horned frogs"], "TXTECH": ["texas tech", "red raiders"],
        "UCF": ["ucf", "knights"], "UTAH": ["utah", "utes"],
        "WVIR": ["west virginia", "mountaineers"], "IOWAST": ["iowa state", "cyclones"],
        "BOSCOL": ["boston college", "eagles"], "CAH": ["california", "cal", "golden bears"],
        "CLMSN": ["clemson", "tigers"], "DUKE": ["duke", "blue devils"],
        "FLST": ["florida state", "seminoles"], "GTECH": ["georgia tech", "yellow jackets"],
        "LOU": ["louisville", "cardinals"], "MIA": ["miami", "hurricanes"],
        "NCST": ["nc state", "wolfpack"], "NCAR": ["north carolina", "tar heels"],
        "PITT": ["pittsburgh", "pitt", "panthers"], "SMU": ["smu", "mustangs"],
        "STAN": ["stanford", "cardinal"], "SYRA": ["syracuse", "orange"],
        "VIR": ["virginia", "cavaliers"], "VTECH": ["virginia tech", "hokies"],
        "WAKE": ["wake forest", "demon deacons"],
        "GNZG": ["gonzaga", "bulldogs"], "UCONN": ["uconn", "connecticut", "huskies"],
        "MARQ": ["marquette", "golden eagles"], "CREIGH": ["creighton", "bluejays"],
        "XAV": ["xavier", "musketeers"], "VILL": ["villanova", "wildcats"],
        "SDST": ["san diego state", "aztecs"], "MPHS": ["memphis", "tigers"],
        "WICHST": ["wichita state", "shockers"], "DAY": ["dayton", "flyers"],
        "STLOU": ["saint louis", "billikens"], "RICH": ["richmond", "spiders"],
        "GEORGE": ["georgetown", "hoyas"], "PROV": ["providence", "friars"],
        "SETON": ["seton hall", "pirates"], "BUTL": ["butler", "bulldogs"],
        "DEPAUL": ["depaul", "blue demons"], "HARVRD": ["harvard", "crimson"],
    },
    "ncaawb": {
        # Real codes verified against SportsDataIO's actual Teams endpoint
        # for the women's feed specifically — this doesn't have full code
        # parity with the men's ncaab table (e.g. Alabama, Illinois, and
        # Arizona don't appear the same way here), so every code below was
        # individually cross-checked against this exact dataset rather
        # than assumed. 1,058 teams total in this feed across all
        # divisions — this covers major, recognizable D1 programs only.
        "ARK": ["arkansas", "razorbacks"], "AUBRN": ["auburn", "tigers"],
        "BAYL": ["baylor", "bears"], "BOSCOL": ["boston college", "eagles"],
        "BYU": ["byu", "cougars"], "CAH": ["california", "cal", "golden bears"],
        "CIN": ["cincinnati", "bearcats"], "CLMSN": ["clemson", "tigers"],
        "DUKE": ["duke", "blue devils"], "FL": ["florida", "gators"],
        "FLST": ["florida state", "seminoles"], "GA": ["georgia", "bulldogs"],
        "GNZG": ["gonzaga", "bulldogs"], "GTECH": ["georgia tech", "yellow jackets"],
        "HOU": ["houston", "cougars"], "IND": ["indiana", "hoosiers"],
        "IOWA": ["iowa", "hawkeyes"], "IOWAST": ["iowa state", "cyclones"],
        "KANST": ["kansas state", "wildcats"], "LOU": ["louisville", "cardinals"],
        "LSU": ["lsu", "louisiana state", "tigers"], "MARY": ["maryland", "terrapins", "terps"],
        "MIA": ["miami", "hurricanes"], "MICH": ["michigan", "wolverines"],
        "MINNST": ["minnesota", "golden gophers"], "MISS": ["ole miss", "mississippi", "rebels"],
        "MISSR": ["missouri", "tigers"], "MSPST": ["mississippi state", "bulldogs"],
        "MST": ["michigan state", "spartans"], "NCAR": ["north carolina", "tar heels"],
        "NCST": ["nc state", "wolfpack"], "ND": ["notre dame", "fighting irish"],
        "NEBR": ["nebraska", "cornhuskers"], "NW": ["northwestern", "wildcats"],
        "OHIOST": ["ohio state", "buckeyes"], "OKL": ["oklahoma", "sooners"],
        "OKST": ["oklahoma state", "cowboys"], "ORE": ["oregon", "ducks"],
        "PENNST": ["penn state", "nittany lions"], "PITT": ["pittsburgh", "pitt", "panthers"],
        "PUR": ["purdue", "boilermakers"], "RUTGER": ["rutgers", "scarlet knights"],
        "SC": ["south carolina", "gamecocks"], "SMU": ["smu", "mustangs"],
        "STAN": ["stanford", "cardinal"], "SYRA": ["syracuse", "orange"],
        "TCU": ["tcu", "horned frogs"], "TENN": ["tennessee", "volunteers", "vols"],
        "TX": ["texas", "longhorns"], "TXAM": ["texas a&m", "texas am", "aggies"],
        "TXTECH": ["texas tech", "red raiders"], "UCF": ["ucf", "knights"],
        "UCLA": ["ucla", "bruins"], "UCONN": ["uconn", "connecticut", "huskies"],
        "USC": ["usc", "trojans"], "UTAH": ["utah", "utes"],
        "VAND": ["vanderbilt", "commodores"], "VIR": ["virginia", "cavaliers"],
        "VTECH": ["virginia tech", "hokies"], "WASH": ["washington", "huskies"],
        "WISC": ["wisconsin", "badgers"], "WVIR": ["west virginia", "mountaineers"],
        "WAKE": ["wake forest", "demon deacons"],
    },
    "wnba": {
        # Real codes verified against SportsDataIO's actual Teams endpoint.
        # Some of these differ from codes used elsewhere in the codebase
        # (e.g. Smack Chat's room list uses "CON"/"GS"/"PHO"/"WAS" — those
        # were arbitrary labels for chat rooms, not tied to live API
        # matching, so they didn't need to match this exactly). Also
        # includes Portland and Toronto, both new expansion franchises.
        "ATL": ["atlanta", "dream"], "CHI": ["chicago", "sky"],
        "CONN": ["connecticut", "conn", "sun"], "DAL": ["dallas", "wings"],
        "GSV": ["golden state", "valkyries"], "IND": ["indiana", "fever"],
        "LA": ["los angeles", "la", "sparks"], "LV": ["las vegas", "aces"],
        "MIN": ["minnesota", "lynx"], "NY": ["new york", "liberty"],
        "PHX": ["phoenix", "mercury"], "POR": ["portland", "fire"],
        "SEA": ["seattle", "storm"], "TOR": ["toronto", "tempo"],
        "WSH": ["washington", "mystics"],
    },
}


def matches_search(sport: str, team_code: str, query: str) -> bool:
    """
    True if the search query matches this team — checks the raw code itself
    plus every known alias (city, nickname, full name) for that sport.
    Falls back to a plain substring match against the code for leagues
    without an alias table (college sports, soccer, etc.).

    Tolerant of missing spaces (e.g. "whitesox" still matches the "white
    sox" alias) since that's a very natural way for someone to type it.
    """
    query = query.strip().lower()
    if not query:
        return True

    if query in team_code.lower():
        return True

    aliases = TEAM_ALIASES.get(sport, {}).get(team_code, [])
    if any(query in alias for alias in aliases):
        return True

    # space-insensitive fallback — catches "whitesox" against "white sox"
    query_no_spaces = query.replace(" ", "")
    return any(query_no_spaces in alias.replace(" ", "") for alias in aliases)


# Properly-capitalized nickname for display purposes — SportsDataIO's raw
# feed only gives abbreviations ("SF", "LAA"), not friendly names, so this
# is what actually shows up anywhere a team name is displayed on-screen
# (search results, "who has to lose" cards, the scoreboard, etc).
DISPLAY_NAMES = {
    "nfl": {
        "ARI": "Cardinals", "ATL": "Falcons", "BAL": "Ravens", "BUF": "Bills",
        "CAR": "Panthers", "CHI": "Bears", "CIN": "Bengals", "CLE": "Browns",
        "DAL": "Cowboys", "DEN": "Broncos", "DET": "Lions", "GB": "Packers",
        "HOU": "Texans", "IND": "Colts", "JAX": "Jaguars", "KC": "Chiefs",
        "LAC": "Chargers", "LAR": "Rams", "LV": "Raiders", "MIA": "Dolphins",
        "MIN": "Vikings", "NE": "Patriots", "NO": "Saints", "NYG": "Giants",
        "NYJ": "Jets", "PHI": "Eagles", "PIT": "Steelers", "SEA": "Seahawks",
        "SF": "49ers", "TB": "Buccaneers", "TEN": "Titans", "WAS": "Commanders",
    },
    "nba": {
        "ATL": "Hawks", "BOS": "Celtics", "BKN": "Nets", "CHA": "Hornets",
        "CHI": "Bulls", "CLE": "Cavaliers", "DAL": "Mavericks", "DEN": "Nuggets",
        "DET": "Pistons", "GS": "Warriors", "HOU": "Rockets", "IND": "Pacers",
        "LAC": "Clippers", "LAL": "Lakers", "MEM": "Grizzlies", "MIA": "Heat",
        "MIL": "Bucks", "MIN": "Timberwolves", "NO": "Pelicans", "NY": "Knicks",
        "OKC": "Thunder", "ORL": "Magic", "PHI": "76ers", "PHO": "Suns",
        "POR": "Trail Blazers", "SAC": "Kings", "SA": "Spurs", "TOR": "Raptors",
        "UTA": "Jazz", "WAS": "Wizards",
    },
    "mlb": {
        "ARI": "Diamondbacks", "ATL": "Braves", "BAL": "Orioles", "BOS": "Red Sox",
        "CHC": "Cubs", "CHW": "White Sox", "CIN": "Reds", "CLE": "Guardians",
        "COL": "Rockies", "DET": "Tigers", "HOU": "Astros", "KC": "Royals",
        "LAA": "Angels", "LAD": "Dodgers", "MIA": "Marlins", "MIL": "Brewers",
        "MIN": "Twins", "NYM": "Mets", "NYY": "Yankees", "ATH": "Athletics",
        "PHI": "Phillies", "PIT": "Pirates", "SD": "Padres", "SF": "Giants",
        "SEA": "Mariners", "STL": "Cardinals", "TB": "Rays", "TEX": "Rangers",
        "TOR": "Blue Jays", "WSH": "Nationals",
    },
    "nhl": {
        "ANA": "Ducks", "UTA": "Mammoth", "BOS": "Bruins", "BUF": "Sabres",
        "CGY": "Flames", "CAR": "Hurricanes", "CHI": "Blackhawks", "COL": "Avalanche",
        "CBJ": "Blue Jackets", "DAL": "Stars", "DET": "Red Wings", "EDM": "Oilers",
        "FLA": "Panthers", "LA": "Kings", "MIN": "Wild", "MON": "Canadiens",
        "NAS": "Predators", "NJ": "Devils", "NYI": "Islanders", "NYR": "Rangers",
        "OTT": "Senators", "PHI": "Flyers", "PIT": "Penguins", "SJ": "Sharks",
        "SEA": "Kraken", "STL": "Blues", "TB": "Lightning", "TOR": "Maple Leafs",
        "VAN": "Canucks", "VEG": "Golden Knights", "WAS": "Capitals", "WPG": "Jets",
    },
    "ncaaf": {
        "ALA": "Alabama", "ARK": "Arkansas", "AUBRN": "Auburn", "FL": "Florida",
        "GA": "Georgia", "UK": "Kentucky", "LSU": "LSU", "MISS": "Ole Miss",
        "MSPST": "Mississippi State", "MISSR": "Missouri", "OKL": "Oklahoma",
        "SC": "South Carolina", "TENN": "Tennessee", "TX": "Texas",
        "TXAM": "Texas A&M", "VAND": "Vanderbilt",
        "ILL": "Illinois", "IND": "Indiana", "IOWA": "Iowa", "MARY": "Maryland",
        "MICH": "Michigan", "MST": "Michigan State", "MINNST": "Minnesota",
        "NEBR": "Nebraska", "NW": "Northwestern", "OHIOST": "Ohio State",
        "ORE": "Oregon", "PENNST": "Penn State", "PUR": "Purdue",
        "RUTGER": "Rutgers", "UCLA": "UCLA", "USC": "USC", "WASH": "Washington",
        "WISC": "Wisconsin",
        "ARZ": "Arizona", "ARZST": "Arizona State", "BAYL": "Baylor", "BYU": "BYU",
        "CIN": "Cincinnati", "COL": "Colorado", "HOU": "Houston", "KAN": "Kansas",
        "KANST": "Kansas State", "OKST": "Oklahoma State", "TCU": "TCU",
        "TXTECH": "Texas Tech", "UCF": "UCF", "UTAH": "Utah",
        "WVIR": "West Virginia", "IOWAST": "Iowa State",
        "BOSCOL": "Boston College", "CAH": "California", "CLMSN": "Clemson",
        "DUKE": "Duke", "FLST": "Florida State", "GTECH": "Georgia Tech",
        "LOU": "Louisville", "MIA": "Miami", "NCST": "NC State", "NCAR": "North Carolina",
        "PITT": "Pittsburgh", "SMU": "SMU", "STAN": "Stanford", "SYRA": "Syracuse",
        "VIR": "Virginia", "VTECH": "Virginia Tech", "WAKE": "Wake Forest",
        "ND": "Notre Dame", "NAVY": "Navy", "ARMY": "Army",
        "BOISE": "Boise State", "MPHS": "Memphis", "TULANE": "Tulane",
        "TULSA": "Tulsa", "APPLST": "Appalachian State", "COAST": "Coastal Carolina",
        "JMAD": "James Madison", "LOULAF": "Louisiana", "MARSH": "Marshall",
        "SDST": "San Diego State", "NEVADA": "Nevada", "HAWAII": "Hawaii",
        "UTSA": "UTSA", "UAB": "UAB", "TROY": "Troy", "LIBRTY": "Liberty",
        "UNLV": "UNLV",
    },
    "ncaab": {
        "ALA": "Alabama", "ARK": "Arkansas", "AUBRN": "Auburn", "FL": "Florida",
        "GA": "Georgia", "UK": "Kentucky", "LSU": "LSU", "MISS": "Ole Miss",
        "MSPST": "Mississippi State", "MISSR": "Missouri", "OKL": "Oklahoma",
        "SC": "South Carolina", "TENN": "Tennessee", "TX": "Texas",
        "TXAM": "Texas A&M", "VAND": "Vanderbilt",
        "ILL": "Illinois", "IND": "Indiana", "IOWA": "Iowa", "MARY": "Maryland",
        "MICH": "Michigan", "MST": "Michigan State", "MINNST": "Minnesota",
        "NEBR": "Nebraska", "NW": "Northwestern", "OHIOST": "Ohio State",
        "ORE": "Oregon", "PENNST": "Penn State", "PUR": "Purdue",
        "RUTGER": "Rutgers", "UCLA": "UCLA", "USC": "USC", "WASH": "Washington",
        "WISC": "Wisconsin",
        "ARZ": "Arizona", "ARZST": "Arizona State", "BAYL": "Baylor", "BYU": "BYU",
        "CIN": "Cincinnati", "COL": "Colorado", "HOU": "Houston", "KAN": "Kansas",
        "KANST": "Kansas State", "OKST": "Oklahoma State", "TCU": "TCU",
        "TXTECH": "Texas Tech", "UCF": "UCF", "UTAH": "Utah",
        "WVIR": "West Virginia", "IOWAST": "Iowa State",
        "BOSCOL": "Boston College", "CAH": "California", "CLMSN": "Clemson",
        "DUKE": "Duke", "FLST": "Florida State", "GTECH": "Georgia Tech",
        "LOU": "Louisville", "MIA": "Miami", "NCST": "NC State", "NCAR": "North Carolina",
        "PITT": "Pittsburgh", "SMU": "SMU", "STAN": "Stanford", "SYRA": "Syracuse",
        "VIR": "Virginia", "VTECH": "Virginia Tech", "WAKE": "Wake Forest",
        "GNZG": "Gonzaga", "UCONN": "UConn", "MARQ": "Marquette", "CREIGH": "Creighton",
        "XAV": "Xavier", "VILL": "Villanova", "SDST": "San Diego State",
        "MPHS": "Memphis", "WICHST": "Wichita State", "DAY": "Dayton",
        "STLOU": "Saint Louis", "RICH": "Richmond", "GEORGE": "Georgetown",
        "PROV": "Providence", "SETON": "Seton Hall", "BUTL": "Butler",
        "DEPAUL": "DePaul", "HARVRD": "Harvard",
    },
    "ncaawb": {
        "ARK": "Arkansas", "AUBRN": "Auburn", "BAYL": "Baylor",
        "BOSCOL": "Boston College", "BYU": "BYU", "CAH": "California",
        "CIN": "Cincinnati", "CLMSN": "Clemson", "DUKE": "Duke", "FL": "Florida",
        "FLST": "Florida State", "GA": "Georgia", "GNZG": "Gonzaga",
        "GTECH": "Georgia Tech", "HOU": "Houston", "IND": "Indiana",
        "IOWA": "Iowa", "IOWAST": "Iowa State", "KANST": "Kansas State",
        "LOU": "Louisville", "LSU": "LSU", "MARY": "Maryland", "MIA": "Miami",
        "MICH": "Michigan", "MINNST": "Minnesota", "MISS": "Ole Miss",
        "MISSR": "Missouri", "MSPST": "Mississippi State", "MST": "Michigan State",
        "NCAR": "North Carolina", "NCST": "NC State", "ND": "Notre Dame",
        "NEBR": "Nebraska", "NW": "Northwestern", "OHIOST": "Ohio State",
        "OKL": "Oklahoma", "OKST": "Oklahoma State", "ORE": "Oregon",
        "PENNST": "Penn State", "PITT": "Pittsburgh", "PUR": "Purdue",
        "RUTGER": "Rutgers", "SC": "South Carolina", "SMU": "SMU",
        "STAN": "Stanford", "SYRA": "Syracuse", "TCU": "TCU", "TENN": "Tennessee",
        "TX": "Texas", "TXAM": "Texas A&M", "TXTECH": "Texas Tech", "UCF": "UCF",
        "UCLA": "UCLA", "UCONN": "UConn", "USC": "USC", "UTAH": "Utah",
        "VAND": "Vanderbilt", "VIR": "Virginia", "VTECH": "Virginia Tech",
        "WASH": "Washington", "WISC": "Wisconsin", "WVIR": "West Virginia",
        "WAKE": "Wake Forest",
    },
    "wnba": {
        "ATL": "Dream", "CHI": "Sky", "CONN": "Sun", "DAL": "Wings",
        "GSV": "Valkyries", "IND": "Fever", "LA": "Sparks", "LV": "Aces",
        "MIN": "Lynx", "NY": "Liberty", "PHX": "Mercury", "POR": "Fire",
        "SEA": "Storm", "TOR": "Tempo", "WSH": "Mystics",
    },
}


def get_display_name(sport: str, team_code: str) -> str:
    """
    Returns the friendly team name (e.g. "Giants") for display anywhere on
    screen. Falls back to the raw code if this sport/team isn't in the
    table (college sports, soccer, etc. — those show the code as-is).
    """
    return DISPLAY_NAMES.get(sport, {}).get(team_code, team_code)
